/* ============================================================
   Portfolio type definitions — redesigned data model
   ============================================================
   Source of truth for all portfolio data shapes.
   Existing components may still import from portfolio.ts directly;
   these types will be re-exported from there as the migration
   progresses. */

// ─── Navigation ──────────────────────────────────────────────

export interface NavItem {
  label: string;
  href: string;
}

// ─── Social ──────────────────────────────────────────────────

export interface SocialLink {
  name: string;
  url: string;
  icon: string;
}

// ─── Projects ────────────────────────────────────────────────

/** Project category for filtering and visual treatment */
export type ProjectCategory =
  | "Sports Analytics / Simulation"
  | "Health AI"
  | "Business Analytics"
  | "Risk Analytics"
  | "Education Analytics / ML"
  | "API Data Product"
  | "Web Product"
  | "Machine Learning";

/** Base project shape — used in portfolio data */
export interface Project {
  id: number;
  title: string;
  slug: string;
  description: string;
  technologies: string[];
  category: ProjectCategory;
  liveUrl?: string;
  githubUrl?: string;
  highlights: string[];
  image?: string;
  featured: boolean;
  /** Display order — lower = first */
  order: number;
  date: string;
}

/** Extended project with case-study fields (generated by projectHelpers) */
export interface ProjectCaseStudy extends Project {
  result: string;
  timeline: string;
  problem: string;
  approach: string;
  outputs: string[];
  learnings: string[];
  nextSteps: string[];
  visual?: string;
  linkedinPostId?: string;
}

// ─── Skills ──────────────────────────────────────────────────

export interface SkillCategory {
  title: string;
  icon: string;
  skills: { name: string; level: number }[];
}

export interface Skill {
  category: string;
  items: string[];
}

// ─── Education ───────────────────────────────────────────────

export interface Education {
  institution: string;
  degree: string;
  field: string;
  year: string;
  graduationYear: number;
  description?: string;
}

// ─── Hero ────────────────────────────────────────────────────

export interface HeroData {
  eyebrow: string;
  title: string;
  description: string;
  cta: { label: string; href: string }[];
}

// ─── Workflow card (hero visual) ─────────────────────────────

export interface WorkflowStep {
  step: number;
  label: string;
  detail: string;
}

// ─── About ───────────────────────────────────────────────────

export interface AboutData {
  title: string;
  description: string[];
  currentFocus: string[];
}

// ─── Contact ─────────────────────────────────────────────────

export interface ContactData {
  title: string;
  description: string;
  email: string;
  links: SocialLink[];
}

// ─── Blog ────────────────────────────────────────────────────

export interface BlogPost {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  tags: string[];
  category?: string;
  readTime?: string;
  linkedProject?: string;
  content?: string;
}

// ─── Portfolio aggregate ─────────────────────────────────────

export interface PortfolioData {
  hero: HeroData;
  about: AboutData;
  projects: Project[];
  skills: Skill[];
  education: Education[];
  contact: ContactData;
  navigation: NavItem[];
  socialLinks: SocialLink[];
  workflow: WorkflowStep[];
  /** Section heading copy per section */
  sectionCopy: {
    projects: { title: string; subtitle: string };
    blog: { title: string; subtitle: string };
    about: { title: string };
    contact: { title: string; description: string };
  };
}
